### ISSUE TITLE
footer of message box is buggy

### ISSUE THREAD

**Issue by nop33** [nop33/indico-styleguide#12]

**Comment by nop33** [comment]
in `indico/indico/htdocs/sass/partials/_messageboxes.scss`:
```scss
$default-spacing: 10px;

.message-box-footer {
        ...
        margin: $default-spacing -$default-spacing -$default-spacing -$default-spacing;
        ...
}
```
This in Indico translates to `margin: 10px -10px -10px -10px;` but in the styleguide it translates to `margin: -20px;` as if it performs the mathematical expression.
